source 'http://rubygems.org'

gem 'nats'
gem 'datamapper', '>= 0.10.2'
gem 'do_sqlite3', :require => nil
gem 'dm-sqlite-adapter'
gem 'em-http-request'
gem 'json'
gem 'uuidtools'
gem 'ruby-hmac', :require => 'hmac-sha1'
gem 'thin'
gem 'sinatra'

gem 'vcap_common', :require => ['vcap/common', 'vcap/component'], :git => 'git://github.com/IronFoundry/vcap-common.git', :branch => 'ironfoundry'
gem 'vcap_logging', :require => ['vcap/logging'], :git => 'git://github.com/IronFoundry/common.git', :branch => 'ironfoundry'
gem 'vcap_services_base', :git => 'git://github.com/IronFoundry/vcap-services-base.git', :branch => 'ironfoundry'
gem 'warden-client', :require => ['warden/client'], :git => 'git://github.com/cloudfoundry/warden.git', :ref => '21f9a32ab50'
gem 'warden-protocol', :require => ['warden/protocol'], :git => 'git://github.com/cloudfoundry/warden.git', :ref => '21f9a32ab50'

platforms :ruby do
  gem 'eventmachine', :git => 'git://github.com/cloudfoundry/eventmachine.git', :branch => 'release-0.12.11-cf'
end

platforms :mingw do
  # gems for mssql_node, which only runs on Windows
  gem 'eventmachine', '>= 1.0.0.rc.4'
  gem 'win32-service'
  gem 'win32-eventlog'
  gem 'tiny_tds'
end

group :test do
  gem 'rake'
  gem 'rspec'
  gem 'simplecov'
  gem 'ci_reporter'
end
