---
cloud_controller_uri: api.vcap.me
service:
  name: mssb
  version: "1.0"
  description: "Microsoft Service Bus message queue"
  plans: ["free"]
  default_plan: free
  tags: ["mssb", "mssb-1.0-beta", "message-queue", "Microsoft Service Bus"]
  timeout: 15
ip_route: localhost
#proxy:
#   host: proxy
#   port: 8080
#   keepalive: true
index: 0
token: changemssbtoken
logging:
  level: error
  # file: C:/IronFoundry/mssb/log/mssb_gateway.log
mbus: nats://nats:nats@192.168.171.129:4222
pid: C:/IronFoundry/mssb/run/mssb_gateway.pid
plan_management:
  plans:
    free:
      low_water: 10
      high_water: 180
      #allow_over_provisioning: false
node_timeout: 30 # NB: very important, related to op_time_limit
# z_interval: 30
# check_orphan_interval: 3600
# double_check_orphan_interval: 300
# max_nats_payload: 1048576
