---
capacity: 200
plan: free
local_db: sqlite3:C:/IronFoundry/mssb/db/mssb_node.db
base_dir: C:/IronFoundry/mssb
mbus: nats://nats:nats@192.168.171.129:4222
index: 0

logging:
  level: debug
  # file: C:/IronFoundry/mssb/log/mssb_node.log

max_memory: 16
pid: C:/IronFoundry/mssb/run/mssb_node.pid
node_id: mssb_node_free_1

supported_versions: ["1.0"]
default_version: "1.0"

migration_nfs: C:/var/mnt/appcloud

fqdn_hosts: true # NB: must be true
op_time_limit: 30 # NB: very important

# ip_route: 127.0.0.1 # NB: optional, only set if necessary
# mssb_start_timeout: 5
# z_interval: 30
# max_nats_payload: 1048576
