---
capacity: 200
plan: free
local_db: sqlite3:C:/var/vcap/services/mssb/mssb_node.db
base_dir: C:/var/vcap/services/mssb/instances
mbus: nats://localhost:4222
index: 0

logging:
  level: debug
  file: C:/var/vcap/sys/log/mssb_node.log

ip_route: 127.0.0.1
max_memory: 16
node_id: mssb_node_free_1
pid: C:/var/vcap/sys/run/mssb_node.pid
migration_nfs: /mnt/appcloud

# TODO probably don't need
# port_range:
#   first: 10001
#   last: 20000
# admin_port_range:
#   first: 20001
#   last: 30000

# mssb_start_timeout: 5
# z_interval: 30
# max_nats_payload: 1048576
# fqdn_hosts: false
# op_time_limit: 6
